language: node_js
node_js:
  - 8
branches:
  only:
    - master
before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_API_KEY
deploy:
  - provider: npm
    email: luke@c2cschools.com
    skip_cleanup: true
    api_key: "$NPM_API_KEY"
    on:
      all_branches: true
env:
  global:
    # NPM_API_KEY
    - secure: "uTRd9mL3qlnM8hS9PL0iKg6NH0Ez8LuaAe9Uy5UhrT3RC1El4Wfti9alvQfV4+xceRXuAdN7aJwq50rLeh6ABQZm8T9f5ikh0RB4D/SAy/KOP2kJCHW4ChxCu4/65y4NX/rHWd4cIs9p2ajh42AQTy9kEqPKohLeofjqa6FFAZLEGD5jcgNwIw9gk2pG4VicEvoIEMdU2LC3l7281S4X+ki5L8xXev84zfNmhPG4+kbnMf7ZMkEZXs2IXl6fXiSQdYUxsxa40laFksb0vuC66dJ9N+8NSE5VvOcDjyWM/bvAW6Myhg69DjhFFNs/V6+CLm+KUN9nPYATd9zZls14wSyuNhJX6yoyq/tRtvfT3t4ngwY4Mg8r/ImYU0UGZp5FoFA+luisptMcjemj+ZcsFM8AIyPmeox03LtYr2tO/RWeDuCcPkdAg79xd0xNNDWji0vgeiCvf50Waw5B1+bZGHF5mLnsk1Q0ff1gNRbIdHCLGjcZNKJLfidr3ccMIpJivM60tU+8sra9EcWSbPz95XnwisG4Hq2UbmKKP03gJoC883r6eRuLPR8wObsoCNSEia4c7l99Djtak5eYJtTzSD+qLOI4kQJAqegRz4PVQnA0/lZqF/Q6xzl90ILgQCA5rKeONq+WdeNh4xAwgjKT1khxyXI9OfiEt6i9TdASAks="
notifications:
  slack:
    secure: "K44zWe/YccokqoACOGZ4n/IYQX97IAbDS1hd/Ze4QRcV3s6e5urzFUDcXnRkqGQ7Y4SP5j4snwW7rPPDo9EAysc67gFb9nBrVjccf3yhPcv6dIPgcMHDfzd3VPufNtYnLhuPfFd88vfryHayaicHXZD734zGyqqApMe98gq0on7M3qGa4QXMuyWi9pqxOeQZNhzkBRBT379SEx7gEoMQ/qtZbuE9cG71NGYGEcppAP4q4LdoWWx274KF9VKlIwxXy+iVdR8YOZLvKEBb9uxmWek3W0/EbVc3LZIZWSeTQgQy/3iT0mqcekUkbJt1iucJfwhTgiBH8/SnH/qlni1WhB6zCmcLU0xlf2cSJP3VD5TIh5zNvp/AR9aDum8qTc+rm3uz8xPru6qdy+xVYnCcXSks7yHReXMzMfZMPiHoto3cxghida8IARJxHJ3lQ3QMd9k7GsnC3Q8cXbY6PQARehNPGZAc2kIzhZU6Wlf6V8+JuhuFkeQzzieqXwI1RKotvX64xlh+OlfyKU2rP23aouf293XbcGcZDDmuOneZcz9qMplzptDx6qP6pftNxRXgeLWT/MF+uf8zpV6rQ5UrbEaFVLz2365RjZvkQNhi6UHcUEh6cC1icvYKX2APqIw7OokJKBiQfgF/+s94F31bxLtdc+TkgKo7aJw5yuvn1vU="

